name: riverpod_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  altfire_authenticator: ^1.0.0
  altfire_configurator: ^1.0.0
  altfire_messenger: ^0.2.0
  altfire_tracker: ^1.0.0
  awaitable_button: ^1.3.0
  cached_network_image: ^3.4.0
  clock: ^1.1.1
  cloud_firestore: ^5.6.8
  collection: ^1.16.0
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.1.1
  dio: ^5.7.0
  firebase_core: ^3.14.0
  firebase_dynamic_links: ^6.0.4
  firebase_performance: ^0.10.0+2
  firebase_storage: ^12.4.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^15.2.3
  google_sign_in: ^6.3.0
  hooks_riverpod: ^2.5.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  linked_scroll_controller: ^0.2.0
  package_info_plus: ^8.3.0
  retrofit: ^4.6.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  simple_logger: ^1.9.0+1
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  sort_key_generator: ^0.2.1
  tuple: ^2.0.0
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  version: ^3.0.2

dev_dependencies:
  altive_lints: ^1.21.0
  build_runner: ^2.4.12
  custom_lint: ^0.7.5
  flutter_gen_runner: ^5.11.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  go_router_builder: ^2.8.2
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  slang_build_runner: ^4.8.0
  retrofit_generator: ^9.2.0

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    rive: false
    lottie: false
  assets:
    outputs:
      style: dot-delimiter

flutter:
  uses-material-design: true